<?php

namespace App\Services;

use App\Models\User;
use App\Models\Wallet;
use Illuminate\Support\Facades\Log;

/**
 * Educational Scam Simulator Service
 * 
 * ⚠️ FOR EDUCATIONAL PURPOSES ONLY ⚠️
 * 
 * This service demonstrates how fraudulent cryptocurrency platforms
 * manipulate user balances and create fake trading environments.
 * 
 * NEVER use this for actual fraud or deception.
 */
class EducationalScamSimulator
{
    /**
     * Simulate artificial profit generation
     * This shows how scammers create fake profits in user accounts
     */
    public function generateArtificialProfits(User $user, float $profitPercentage = 5.0): array
    {
        Log::info('EDUCATIONAL SIMULATION: Generating artificial profits', [
            'user_id' => $user->id,
            'profit_percentage' => $profitPercentage,
            'warning' => 'This is a simulation - no real money involved'
        ]);

        $wallets = Wallet::where('user_id', $user->id)->get();
        $results = [];

        foreach ($wallets as $wallet) {
            if ($wallet->cryptocurrency_symbol !== 'USD') {
                $originalBalance = (float) $wallet->balance;
                $fakeProfit = $originalBalance * ($profitPercentage / 100);
                $newBalance = $originalBalance + $fakeProfit;

                // Update the fake balance in database
                $wallet->update(['balance' => number_format($newBalance, 8, '.', '')]);

                $results[] = [
                    'currency' => $wallet->cryptocurrency_symbol,
                    'original_balance' => $originalBalance,
                    'fake_profit' => $fakeProfit,
                    'new_balance' => $newBalance,
                    'educational_note' => 'This profit is completely fake - generated by database manipulation'
                ];
            }
        }

        return [
            'success' => true,
            'message' => 'SIMULATION: Artificial profits generated',
            'profits' => $results,
            'educational_warning' => 'These profits exist only in the database and have no real value'
        ];
    }

    /**
     * Simulate withdrawal blocking mechanisms
     * This demonstrates common tactics used to prevent withdrawals
     */
    public function simulateWithdrawalBlocking(User $user, string $currency, float $amount): array
    {
        Log::info('EDUCATIONAL SIMULATION: Demonstrating withdrawal blocking', [
            'user_id' => $user->id,
            'currency' => $currency,
            'amount' => $amount,
            'warning' => 'This demonstrates fraud tactics - for education only'
        ]);

        // Common scam tactics for blocking withdrawals
        $blockingTactics = [
            [
                'type' => 'verification_required',
                'message' => 'Account verification required. Please upload additional documents.',
                'fake_requirement' => 'Submit passport, utility bill, and selfie with ID'
            ],
            [
                'type' => 'tax_payment',
                'message' => 'Tax payment required before withdrawal.',
                'fake_requirement' => 'Pay 15% tax fee: $' . number_format($amount * 0.15, 2)
            ],
            [
                'type' => 'vip_upgrade',
                'message' => 'Upgrade to VIP status required for large withdrawals.',
                'fake_requirement' => 'Pay $500 VIP upgrade fee'
            ],
            [
                'type' => 'gas_fee',
                'message' => 'Network gas fee required for blockchain transaction.',
                'fake_requirement' => 'Pay $200 gas fee for transaction processing'
            ],
            [
                'type' => 'minimum_balance',
                'message' => 'Minimum balance requirement not met.',
                'fake_requirement' => 'Maintain minimum $1000 balance for withdrawals'
            ]
        ];

        $selectedTactic = $blockingTactics[array_rand($blockingTactics)];

        return [
            'success' => false,
            'blocked' => true,
            'tactic_used' => $selectedTactic,
            'educational_explanation' => [
                'what_happened' => 'The system blocked your withdrawal using a common scam tactic',
                'why_scammers_do_this' => 'To extract more money from victims before disappearing',
                'red_flags' => [
                    'Unexpected fees after deposit',
                    'Constantly changing requirements',
                    'Pressure to pay quickly',
                    'No customer service response'
                ]
            ],
            'warning' => 'In real scams, these fees lead to more demands and eventual loss of all funds'
        ];
    }

    /**
     * Generate fake transaction IDs
     * This shows how scammers create fake blockchain transactions
     */
    public function generateFakeTransactionId(string $currency = 'BTC'): array
    {
        // Generate realistic-looking but fake transaction IDs
        $fakeTransactionIds = [
            'BTC' => '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa' . bin2hex(random_bytes(16)),
            'ETH' => '0x' . bin2hex(random_bytes(32)),
            'USDT' => '0x' . bin2hex(random_bytes(32)),
        ];

        $fakeId = $fakeTransactionIds[$currency] ?? ('fake_' . bin2hex(random_bytes(20)));

        Log::info('EDUCATIONAL SIMULATION: Generated fake transaction ID', [
            'currency' => $currency,
            'fake_tx_id' => $fakeId,
            'warning' => 'This transaction ID is completely fake'
        ]);

        return [
            'transaction_id' => $fakeId,
            'currency' => $currency,
            'status' => 'pending',
            'educational_note' => 'This transaction ID is fake and will not appear on any blockchain explorer',
            'how_to_verify' => [
                'BTC' => 'Check on blockchain.info or blockchair.com',
                'ETH' => 'Check on etherscan.io',
                'USDT' => 'Check on etherscan.io (if ERC-20) or omniexplorer.info (if Omni)'
            ]
        ];
    }

    /**
     * Simulate fake investment plans
     * This demonstrates unrealistic return promises
     */
    public function generateFakeInvestmentPlans(): array
    {
        $fakePlans = [
            [
                'name' => 'Basic AI Trading Bot',
                'daily_return' => '8-12%',
                'minimum_investment' => 100,
                'duration' => '30 days',
                'fake_features' => [
                    'AI-powered trading algorithms',
                    'Guaranteed daily profits',
                    'Zero risk investment',
                    'Instant withdrawals'
                ],
                'red_flags' => [
                    'Guaranteed returns (impossible in real trading)',
                    'Unrealistically high daily returns',
                    'No risk disclosure',
                    'Pressure to invest quickly'
                ]
            ],
            [
                'name' => 'Premium Arbitrage System',
                'daily_return' => '15-25%',
                'minimum_investment' => 500,
                'duration' => '60 days',
                'fake_features' => [
                    'Cross-exchange arbitrage',
                    'Professional trading team',
                    'Compound interest system',
                    'VIP customer support'
                ],
                'red_flags' => [
                    'Extremely high returns',
                    'Vague explanation of strategy',
                    'No regulatory compliance mentioned',
                    'Testimonials from fake users'
                ]
            ]
        ];

        return [
            'plans' => $fakePlans,
            'educational_warning' => 'Real investment returns are never guaranteed and legitimate platforms never promise such high daily returns',
            'legitimate_alternatives' => [
                'Regulated investment platforms',
                'Traditional index funds (5-10% annual return)',
                'Government bonds (2-5% annual return)',
                'Diversified cryptocurrency portfolios'
            ]
        ];
    }

    /**
     * Simulate admin manipulation capabilities
     * This shows what scam operators can control
     */
    public function getAdminManipulationCapabilities(): array
    {
        return [
            'balance_manipulation' => [
                'description' => 'Admins can instantly change any user balance',
                'example' => 'UPDATE wallets SET balance = 50000 WHERE user_id = 123',
                'impact' => 'Users see fake profits to encourage more deposits'
            ],
            'withdrawal_control' => [
                'description' => 'Admins can block or approve withdrawals selectively',
                'example' => 'Allow small withdrawals initially, block large ones',
                'impact' => 'Creates false sense of legitimacy'
            ],
            'fake_notifications' => [
                'description' => 'Send fake profit notifications and trading alerts',
                'example' => 'Your AI bot earned $500 today! Invest more to maximize profits',
                'impact' => 'Psychological manipulation to increase investments'
            ],
            'user_targeting' => [
                'description' => 'Identify high-value targets for personalized scams',
                'example' => 'Flag users with large balances for VIP treatment',
                'impact' => 'Maximize extraction from wealthy victims'
            ],
            'social_proof_manipulation' => [
                'description' => 'Create fake user testimonials and success stories',
                'example' => 'Display fake leaderboards and profit screenshots',
                'impact' => 'Convince new users the platform is legitimate'
            ]
        ];
    }
}