<?php

require_once __DIR__ . '/vendor/autoload.php';

use Illuminate\Http\Request;
use App\Http\Controllers\Api\DepositController;
use App\Services\EducationalDepositService;
use App\Models\User;

// Bootstrap Laravel
$app = require_once __DIR__ . '/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

echo "🧪 Testing Deposit Functionality\n";
echo "================================\n\n";

try {
    // Test 1: Generate Deposit Address
    echo "1. Testing Generate Deposit Address...\n";
    
    $user = User::first();
    if (!$user) {
        echo "❌ No users found. Please create a user first.\n";
        exit(1);
    }
    
    $depositService = app(EducationalDepositService::class);
    $result = $depositService->generateDepositAddress($user, 'BTC');
    
    if ($result['success']) {
        echo "✅ Bitcoin address generated: " . $result['address'] . "\n";
        echo "   QR Code: " . ($result['qr_code'] ? 'Generated' : 'Not generated') . "\n";
    } else {
        echo "❌ Failed to generate address: " . $result['message'] . "\n";
    }
    
    echo "\n";
    
    // Test 2: Simulate Crypto Deposit
    echo "2. Testing Simulate Crypto Deposit...\n";
    
    $result = $depositService->simulateCryptoDeposit($user, 'BTC', 0.001);
    
    if ($result['success']) {
        echo "✅ Crypto deposit simulated successfully\n";
        echo "   Deposit ID: " . $result['deposit']->id . "\n";
        echo "   Amount: " . $result['deposit']->amount . " " . $result['deposit']->currency . "\n";
        echo "   Status: " . $result['deposit']->status . "\n";
    } else {
        echo "❌ Failed to simulate deposit: " . $result['message'] . "\n";
    }
    
    echo "\n";
    
    // Test 3: Create Deposit with Proof (without actual file)
    echo "3. Testing Create Deposit with Proof...\n";
    
    $data = [
        'user_id' => $user->id,
        'currency' => 'ETH',
        'amount' => 0.1,
        'wallet_address' => '0x742d35Cc6634C0532925a3b8D4C0532925a3b8D4',
        'network' => 'Ethereum',
        'transaction_image' => null, // No actual file for testing
    ];
    
    $result = $depositService->createDepositWithProof($data);
    
    if ($result['success']) {
        echo "✅ Deposit with proof created successfully\n";
        echo "   Deposit ID: " . $result['deposit']->id . "\n";
        echo "   Amount: " . $result['deposit']->amount . " " . $result['deposit']->currency . "\n";
        echo "   Status: " . $result['deposit']->status . "\n";
        echo "   Network: " . $result['deposit']->network . "\n";
    } else {
        echo "❌ Failed to create deposit with proof: " . $result['message'] . "\n";
    }
    
    echo "\n";
    
    // Test 4: Get User Deposits
    echo "4. Testing Get User Deposits...\n";
    
    $result = $depositService->getUserDeposits($user);
    
    if ($result['success']) {
        echo "✅ Retrieved user deposits successfully\n";
        echo "   Total deposits: " . $result['deposits']->total() . "\n";
        echo "   Summary: " . json_encode($result['summary'], JSON_PRETTY_PRINT) . "\n";
    } else {
        echo "❌ Failed to get user deposits: " . $result['message'] . "\n";
    }
    
    echo "\n";
    
    // Test 5: Test Different Currencies
    echo "5. Testing Different Currencies...\n";
    
    $currencies = ['ETH', 'USDT', 'BNB', 'SOL'];
    
    foreach ($currencies as $currency) {
        $result = $depositService->generateDepositAddress($user, $currency);
        if ($result['success']) {
            echo "✅ {$currency} address: " . substr($result['address'], 0, 20) . "...\n";
        } else {
            echo "❌ Failed to generate {$currency} address\n";
        }
    }
    
    echo "\n";
    echo "🎉 All deposit functionality tests completed!\n";
    echo "\n";
    
    // Educational Warning
    echo "⚠️  EDUCATIONAL WARNING:\n";
    echo "This system demonstrates how scam platforms handle deposits.\n";
    echo "In real scams:\n";
    echo "- Generated addresses belong to scammers\n";
    echo "- Real money is collected while fake balances are shown\n";
    echo "- Withdrawal attempts are blocked with various excuses\n";
    echo "- Never send real money to addresses generated by this system!\n";
    
} catch (Exception $e) {
    echo "❌ Test failed with error: " . $e->getMessage() . "\n";
    echo "Stack trace:\n" . $e->getTraceAsString() . "\n";
    exit(1);
}